### Neural Network

In [42]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import warnings
warnings.filterwarnings('ignore')

In [43]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [44]:
model = Sequential([
    Dense(2, input_dim=2, activation='sigmoid'),  
    Dense(1, activation='sigmoid')               
])

In [45]:
model.compile(
    optimizer='sgd',             
    loss='binary_crossentropy',   
    metrics=['accuracy']
)

In [46]:
history = model.fit(X, y, epochs=50, verbose=0)

In [47]:
predictions = model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step


In [48]:
np.round(predictions, 3)

array([[0.466],
       [0.492],
       [0.472],
       [0.495]], dtype=float32)

In [49]:
print("\nWeights and Biases:")
for layer in model.layers:
    weights, biases = layer.get_weights()
    print(f"Weights:\n{weights}\nBiases:\n{biases}\n")



Weights and Biases:
Weights:
[[-0.4192162  -0.56263286]
 [-0.6919483   0.42484555]]
Biases:
[-0.00197177  0.00013312]

Weights:
[[-0.49199077]
 [ 0.20061906]]
Biases:
[0.01016435]

